apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.app }}-{{ .Values.version | replace "." "" | replace "/" "-" | replace "_" "" }}-{{ .Values.build }}-hpa
spec:
  maxReplicas: {{ .Values.deployment.hpa.maxReplicas | default 8 }}
  minReplicas: {{ .Values.deployment.replicas | default 2 }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app }}-{{ .Values.version | replace "." "" | replace "/" "-" | replace "_" "" }}-{{ .Values.build }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.deployment.hpa.resources.cpu.targetAverageUtilization | default 60 }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.deployment.hpa.resources.memory.targetAverageUtilization | default 80 }}
